# Generated by Django 3.1.5 on 2021-01-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210129_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='room',
            name='user_name',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
