# Generated by Django 3.1.5 on 2021-01-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210130_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=False, max_length=100)),
                ('code', models.CharField(default=False, max_length=8, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='user_name',
        ),
    ]
